### ISSUE TITLE
Loading files without web server

### ISSUE THREAD

**Issue by nadendlaprasad** [googlecreativelab/teachable-machine-boilerplate#2]
could you please let me know how can i build and load the files without using budo or any other web server?

can i do using the following command ?
**browserify main.js --debug | exorcist bundle.js.map > bundle.js**

**Comment by HalfdanJ** [comment]
You can run `npm build` which runs `browserify main.js -o dist/build.js`, this makes a static version of the site that the `index.html` file is referring to, so if you opening that file wont require a webserver. This is how the [demo](https://googlecreativelab.github.io/teachable-machine-boilerplate/) is generated and hosted.

**Comment by nadendlaprasad** [comment]
Thank you.
