### ISSUE TITLE
[Violation] 'requestAnimationFrame' handler took 218ms

### ISSUE THREAD

**Issue by nadendlaprasad** [googlecreativelab/teachable-machine-boilerplate#3]
When i'm running the model, program is throwing these warning **[Violation] 'requestAnimationFrame' handler took 218ms** messages. This is happening even when i run the model on GPU  machine. Any idea how to improve the performance or what's causing the model to run slowly ? I can observe too much delay sometimes. I am thinking this warning message may be causing the model to run slowly. am i right ?

**Comment by HalfdanJ** [comment]
Hmm, I think it might be worth posting on github.com/PAIR-code/deeplearnjs as that is where the model lives. 

I have sometimes noticed that my browser crashes the webgl context, and I need to reboot my machine to fix it.

**Comment by nadendlaprasad** [comment]
Thanks for the reply. sure, i'll post this on https://github.com/PAIR-code/deeplearnjs/
