### ISSUE TITLE
The training numbers don't change with different things in front of the camera

### ISSUE THREAD

**Issue by ToonTalk** [googlecreativelab/teachable-machine-boilerplate#4]
When I train using

https://googlecreativelab.github.io/teachable-machine-boilerplate/

and for the second class I use a white sheet of paper the confidences don't change.

Doing the same thing at 

https://teachablemachine.withgoogle.com/

works fine

**Comment by ToonTalk** [comment]
Console contains

WebGL: INVALID_OPERATION: readPixels: PIXEL_PACK buffer should not be bound

**Comment by ToonTalk** [comment]
This problem seems to have gone away Maybe close this?

**Comment by HalfdanJ** [comment]
I updated the deeplearnjs version in the boilerplate code, but havent touched the code of live site, so sounds like it has been a bad version of your browser. But glad to hear it has been solved.
